name: Deploy Sphinx Docs

on:
  push:
    branches:
     - main

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Check out repo
       uses: actions/checkout@v4

     - name: Set up Python
       uses: actions/setup-python@v4
       with:
        python-version: '3.11'

     - name: Install dependencies
       run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

     - name: Build docs
       run: |
        sphinx-build -b html docs/source docs/source/_build/html

     - name: Deploy to Github Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/source/_build/html
